"""empty message

Revision ID: a8d3c7e19d20
Revises: 
Create Date: 2019-04-05 17:20:19.364853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8d3c7e19d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_methods', 'code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 방식 코드',
               existing_nullable=False)
    op.alter_column('payment_methods', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 방식 이름',
               existing_nullable=True)
    op.alter_column('payment_methods', 'order',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='순번',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
    op.alter_column('payment_methods', 'status',
               existing_type=mysql.INTEGER(display_width=2),
               comment=None,
               existing_comment='상태 1: 활성화, 0: 비활성화',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('ix_payment_methods_status'), 'payment_methods', ['status'], unique=False)
    op.alter_column('payment_modules', 'code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 모듈 코드',
               existing_nullable=False)
    op.alter_column('payment_modules', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 모듈 이름',
               existing_nullable=True)
    op.alter_column('payment_modules', 'order',
               existing_type=mysql.INTEGER(display_width=10),
               comment=None,
               existing_comment='순번',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
    op.alter_column('payment_modules', 'status',
               existing_type=mysql.INTEGER(display_width=2),
               comment=None,
               existing_comment='상태 1: 활성화, 0: 비활성화',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('ix_payment_modules_status'), 'payment_modules', ['status'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='금액',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('payments', 'id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='인덱스',
               autoincrement=True,
               existing_nullable=False)
    op.alter_column('payments', 'method_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 방식 코드 FK',
               existing_nullable=False)
    op.alter_column('payments', 'module_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment=None,
               existing_comment='결제 모듈 코드 FK',
               existing_nullable=False)
    op.alter_column('payments', 'parent_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='부모 인덱스',
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=mysql.ENUM('WAITING', 'EXPIRED_VBANK', 'CHARGED', 'EXPIRED', 'CANCELED', collation='utf8_unicode_ci'),
               comment=None,
               existing_comment='결제 상태 WAITING: 결제 대기, EXPIRED_VBANK: 가상계좌 입금 시간 초과, CHARGED: 충전, EXPIRED: 만료 (기간 만료), CANCELED: 결제 취소',
               existing_nullable=True,
               existing_server_default=sa.text("'WAITING'"))
    op.alter_column('payments', 'user_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='회원 인덱스',
               existing_nullable=False)
    op.create_index(op.f('ix_payments_method_code'), 'payments', ['method_code'], unique=False)
    op.create_index(op.f('ix_payments_module_code'), 'payments', ['module_code'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.alter_column('payments_lg', 'TID',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=24),
               comment=None,
               existing_comment='거래번호',
               existing_nullable=False)
    op.alter_column('payments_lg', 'account_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment=None,
               existing_comment='가상계좌 발급번호',
               existing_nullable=True)
    op.alter_column('payments_lg', 'account_owner',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment=None,
               existing_comment='계좌주명',
               existing_nullable=True)
    op.alter_column('payments_lg', 'account_payer',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment=None,
               existing_comment='가상계좌 입금자명',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_current_amount',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='현 입금금액',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_flag',
               existing_type=mysql.ENUM('N', 'R', 'I', 'C', charset='utf8', collation='utf8_unicode_ci'),
               comment=None,
               existing_comment='거래종류 N: 해당사항 없음, R: 할당, I: 입금, C: 취소',
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('payments_lg', 'cash_receipt_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment=None,
               existing_comment='현금영수증 승인번호',
               existing_nullable=False)
    op.alter_column('payments_lg', 'cash_receipt_self',
               existing_type=mysql.ENUM('Y', 'N', charset='utf8', collation='utf8_unicode_ci'),
               comment=None,
               existing_comment='현금영수증 자진발급제 유무 Y: 신청, N: 미신청',
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('payments_lg', 'cash_seq_no',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=3),
               comment=None,
               existing_comment='가상계좌 일련번호(은행코드)',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_total_amount',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='입금 누적금액',
               existing_nullable=True)
    op.alter_column('payments_lg', 'finance_auth_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment=None,
               existing_comment='결제기관 승인번호',
               existing_nullable=True)
    op.alter_column('payments_lg', 'finance_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment=None,
               existing_comment='결제기관 코드',
               existing_nullable=False)
    op.alter_column('payments_lg', 'finance_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment=None,
               existing_comment='결제기관명',
               existing_nullable=False)
    op.alter_column('payments_lg', 'hash_data',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               comment=None,
               existing_comment='해쉬데이터',
               existing_nullable=False)
    op.alter_column('payments_lg', 'lg_order_id',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment=None,
               existing_comment='lg 주문번호',
               existing_nullable=False)
    op.alter_column('payments_lg', 'paid_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='결제완료 일시',
               existing_nullable=True)
    op.alter_column('payments_lg', 'payment_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='payment_id',
               existing_nullable=False)
    op.alter_column('payments_lg', 'pcancel_flag',
               existing_type=mysql.ENUM('0', '1', charset='utf8', collation='utf8_unicode_ci'),
               comment=None,
               existing_comment='신용카드 부분취소 가능여부 0: 불가능, 1: 가능',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('payments_lg', 'requested_at',
               existing_type=mysql.TIMESTAMP(),
               comment=None,
               existing_comment='결제시도 시간',
               existing_nullable=True)
    op.alter_column('payments_lg', 'sa_owner',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment=None,
               existing_comment='가상계좌 입금계좌주명',
               existing_nullable=True)
    op.create_index(op.f('ix_payments_lg_TID'), 'payments_lg', ['TID'], unique=False)
    op.drop_index('payments_lg_TID', table_name='payments_lg')
    op.alter_column('users', 'cash',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='캐시',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment=None,
               existing_comment='회원 인덱스',
               autoincrement=True,
               existing_nullable=False)
    op.alter_column('users', 'profits',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='수익금',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profits',
               existing_type=mysql.BIGINT(display_width=20),
               comment='수익금',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='회원 인덱스',
               autoincrement=True,
               existing_nullable=False)
    op.alter_column('users', 'cash',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='캐시',
               existing_nullable=False)
    op.create_index('payments_lg_TID', 'payments_lg', ['TID'], unique=False)
    op.drop_index(op.f('ix_payments_lg_TID'), table_name='payments_lg')
    op.alter_column('payments_lg', 'sa_owner',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment='가상계좌 입금계좌주명',
               existing_nullable=True)
    op.alter_column('payments_lg', 'requested_at',
               existing_type=mysql.TIMESTAMP(),
               comment='결제시도 시간',
               existing_nullable=True)
    op.alter_column('payments_lg', 'pcancel_flag',
               existing_type=mysql.ENUM('0', '1', charset='utf8', collation='utf8_unicode_ci'),
               comment='신용카드 부분취소 가능여부 0: 불가능, 1: 가능',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('payments_lg', 'payment_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='payment_id',
               existing_nullable=False)
    op.alter_column('payments_lg', 'paid_at',
               existing_type=mysql.TIMESTAMP(),
               comment='결제완료 일시',
               existing_nullable=True)
    op.alter_column('payments_lg', 'lg_order_id',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment='lg 주문번호',
               existing_nullable=False)
    op.alter_column('payments_lg', 'hash_data',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=255),
               comment='해쉬데이터',
               existing_nullable=False)
    op.alter_column('payments_lg', 'finance_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment='결제기관명',
               existing_nullable=False)
    op.alter_column('payments_lg', 'finance_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment='결제기관 코드',
               existing_nullable=False)
    op.alter_column('payments_lg', 'finance_auth_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment='결제기관 승인번호',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_total_amount',
               existing_type=mysql.INTEGER(display_width=11),
               comment='입금 누적금액',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_seq_no',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=3),
               comment='가상계좌 일련번호(은행코드)',
               existing_nullable=True)
    op.alter_column('payments_lg', 'cash_receipt_self',
               existing_type=mysql.ENUM('Y', 'N', charset='utf8', collation='utf8_unicode_ci'),
               comment='현금영수증 자진발급제 유무 Y: 신청, N: 미신청',
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('payments_lg', 'cash_receipt_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=10),
               comment='현금영수증 승인번호',
               existing_nullable=False)
    op.alter_column('payments_lg', 'cash_flag',
               existing_type=mysql.ENUM('N', 'R', 'I', 'C', charset='utf8', collation='utf8_unicode_ci'),
               comment='거래종류 N: 해당사항 없음, R: 할당, I: 입금, C: 취소',
               existing_nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('payments_lg', 'cash_current_amount',
               existing_type=mysql.INTEGER(display_width=11),
               comment='현 입금금액',
               existing_nullable=True)
    op.alter_column('payments_lg', 'account_payer',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment='가상계좌 입금자명',
               existing_nullable=True)
    op.alter_column('payments_lg', 'account_owner',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=40),
               comment='계좌주명',
               existing_nullable=True)
    op.alter_column('payments_lg', 'account_num',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=20),
               comment='가상계좌 발급번호',
               existing_nullable=True)
    op.alter_column('payments_lg', 'TID',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=24),
               comment='거래번호',
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_module_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_method_code'), table_name='payments')
    op.alter_column('payments', 'user_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='회원 인덱스',
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=mysql.ENUM('WAITING', 'EXPIRED_VBANK', 'CHARGED', 'EXPIRED', 'CANCELED', collation='utf8_unicode_ci'),
               comment='결제 상태 WAITING: 결제 대기, EXPIRED_VBANK: 가상계좌 입금 시간 초과, CHARGED: 충전, EXPIRED: 만료 (기간 만료), CANCELED: 결제 취소',
               existing_nullable=True,
               existing_server_default=sa.text("'WAITING'"))
    op.alter_column('payments', 'parent_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='부모 인덱스',
               existing_nullable=False)
    op.alter_column('payments', 'module_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 모듈 코드 FK',
               existing_nullable=False)
    op.alter_column('payments', 'method_code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 방식 코드 FK',
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               comment='인덱스',
               autoincrement=True,
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=mysql.BIGINT(display_width=20),
               comment='금액',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_payment_modules_status'), table_name='payment_modules')
    op.alter_column('payment_modules', 'status',
               existing_type=mysql.INTEGER(display_width=2),
               comment='상태 1: 활성화, 0: 비활성화',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('payment_modules', 'order',
               existing_type=mysql.INTEGER(display_width=10),
               comment='순번',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
    op.alter_column('payment_modules', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 모듈 이름',
               existing_nullable=True)
    op.alter_column('payment_modules', 'code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 모듈 코드',
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_methods_status'), table_name='payment_methods')
    op.alter_column('payment_methods', 'status',
               existing_type=mysql.INTEGER(display_width=2),
               comment='상태 1: 활성화, 0: 비활성화',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('payment_methods', 'order',
               existing_type=mysql.INTEGER(display_width=10),
               comment='순번',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
    op.alter_column('payment_methods', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 방식 이름',
               existing_nullable=True)
    op.alter_column('payment_methods', 'code',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_unicode_ci', length=100),
               comment='결제 방식 코드',
               existing_nullable=False)
    # ### end Alembic commands ###
